atoms:
    7:              # (13) CH2O 
        vdw: 124
        charge: 0.14 
    9:             
        vdw: 122   # (44) O Ether
        charge: -0.4

neighbours:
    85: 
        vdw: 127    # H-C-O Alkylether
        charge: 0.03
    100:
        vdw: 125    # CHR2-O-C 
        charge: 0.14
    
